FROM golang:1.26-alpine AS build

WORKDIR /app
COPY . .

RUN apk add --no-cache wget git

RUN	wget https://unpkg.com/htmx-ext-json-enc@2.0.2/dist/json-enc.min.js -O cmd/website/static/admin/htmx/json-enc.js &&\
	wget https://unpkg.com/hyperscript.org@0.9.14/dist/_hyperscript.min.js -O cmd/website/static/admin/htmx/hyperscript.min.js &&\
	wget https://unpkg.com/htmx.org@2.0.4/dist/htmx.min.js -O cmd/website/static/admin/htmx/htmx.min.js && \
    go install github.com/a-h/templ/cmd/templ@v0.3.1020

RUN templ generate && \
    go build -ldflags="-w -s" -o danklyrics-admin ./cmd/http-admin/main.go

FROM alpine:latest AS run

WORKDIR /app
COPY --from=build /app/danklyrics-admin .

EXPOSE 8081

CMD ["./danklyrics-admin"]
