FROM golang:1.26-alpine AS build

WORKDIR /app
COPY . .

RUN go install github.com/a-h/templ/cmd/templ@v0.3.1020

RUN go mod tidy && \
    templ generate && \
    go build -ldflags="-w -s" -o danklyrics-api ./cmd/api/main.go

FROM alpine:latest AS run

WORKDIR /app
COPY --from=build /app/danklyrics-api .

EXPOSE 8081

CMD ["./danklyrics-api"]
